<a href="https://colab.research.google.com/github/Deadkiller43/MLBasics/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Assignment1**

##1. Perform arithmetic operations on NumPy arrays

In [28]:
import numpy as np
a = np.array([[1,2,3],[3,4,5]])
b = np.array([[5,6,7],[7,8,9]])
# There are both ways to do operation 1. By using operator symbol  2. By using function
print(a + b)
#print(np.add(a, b))
print(a - b)
#print(np.subtract(a, b))
print(a * b)
#print(np.multiply(a, b))
print(a / b)
#print(np.divide(a, b))
print(a ** b)
#print(np.power(a, b))
print(b % a)
#print(np.mod(b, a))
print(np.sqrt(a))
print(np.exp(b))
print(np.log(a))
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x.dot(y))
#print(x @ y)
print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[[ 6  8 10]
 [10 12 14]]
[[-4 -4 -4]
 [-4 -4 -4]]
[[ 5 12 21]
 [21 32 45]]
[[0.2        0.33333333 0.42857143]
 [0.42857143 0.5        0.55555556]]
[[      1      64    2187]
 [   2187   65536 1953125]]
[[0 0 1]
 [1 0 4]]
[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
[[ 148.4131591   403.42879349 1096.63315843]
 [1096.63315843 2980.95798704 8103.08392758]]
[[0.         0.69314718 1.09861229]
 [1.09861229 1.38629436 1.60943791]]
[[19 22]
 [43 50]]
18
[4 6 8]
[ 6 12]


##2. Write a script to compute the mean and standard deviation of a NumPy array.

In [29]:
a = np.array([[1,2,3],[3,4,5]])
b = np.array([[5,6,7],[7,8,9]])
print(np.mean(a))
print(np.std(a))
print(np.mean(b))
print(np.std(b))
print(np.mean(a, axis=0, dtype=np.int64))
print(np.mean(a, axis=1, dtype=np.int64))
print(np.mean(b, axis=0))
print(np.mean(b, axis=1))
print(np.std(a, axis=0))
print(np.std(a, axis=1))
print(np.std(b, axis=0))
print(np.std(b, axis=1))

3.0
1.2909944487358056
7.0
1.2909944487358056
[2 3 4]
[2 4]
[6. 7. 8.]
[6. 8.]
[1. 1. 1.]
[0.81649658 0.81649658]
[1. 1. 1.]
[0.81649658 0.81649658]


##3. Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [34]:
c = np.array(range(10, 50, 5))
print(c)
print(type(c))

[10 15 20 25 30 35 40 45]
<class 'numpy.ndarray'>


##4. Reshape the array into a 2x4 matrix.

In [35]:
d = c.reshape(2,4)
print(d)

[[10 15 20 25]
 [30 35 40 45]]


##5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.


In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr1 = arr[1:3, 0:2]
print(arr1)

[[4 5]
 [7 8]]


• Replace all elements greater than 4 with 0.


In [40]:
arr[arr > 4] = 0
print(arr)

[[1 2 3]
 [4 0 0]
 [0 0 0]]


##6. Create two 1D arrays:
##• a = np.array([1, 2, 3])
##• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division

In [45]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + 5)
print(a  - 1)
print(b / 2)

[6 7 8]
[0 1 2]
[2.  2.5 3. ]


##7. Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements

In [51]:
ran = np.random.random((4, 4))
print(np.mean(ran, axis=0))
print(np.max(ran))
print(np.sum(ran))

[0.58136082 0.66090688 0.54667441 0.44742934]
0.9929765901039719
8.94548580000638


##8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2.


In [55]:
arr = np.array([1, 2, 3, 4])
add = 10
res=(arr + add)
print(res)
print(res * 2)

[11 12 13 14]
[22 24 26 28]


##9. Perform advanced slicing and indexing on a 3D array.
##Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
##1 to 100. Perform the following:

In [57]:
arr = np.random.randint(1, 100, (3, 4, 5))

[[[83 19 19 92 56]
  [ 3 89 10 60 18]
  [86 68 34 95 22]
  [14 96 73 37 49]]

 [[92 97 32 47 34]
  [10 84 27  7 46]
  [63 33 71 67 74]
  [61 82  6 80 28]]

 [[76 51 39 13 18]
  [17 96 59  4 24]
  [84 56  5 69 18]
  [11 88  7 37 73]]]


• Extract the second "layer" (i.e., the second 2D array) in the first dimension.

In [60]:
print(arr[1:2, :])

[[[92 97 32 47 34]
  [10 84 27  7 46]
  [63 33 71 67 74]
  [61 82  6 80 28]]]


• Extract the first two rows and the last three columns from each "layer."


In [62]:
print(arr[0:3, 0:2, 2:5])

[[[19 92 56]
  [10 60 18]]

 [[32 47 34]
  [27  7 46]]

 [[39 13 18]
  [59  4 24]]]


• Replace all elements divisible by 3 with -1.

In [63]:
arr[arr % 3 == 0] = -1
print(arr)

[[[83 19 19 92 56]
  [-1 89 10 -1 -1]
  [86 68 34 95 22]
  [14 -1 73 37 49]]

 [[92 97 32 47 34]
  [10 -1 -1  7 46]
  [-1 -1 71 67 74]
  [61 82 -1 80 28]]

 [[76 -1 -1 13 -1]
  [17 -1 59  4 -1]
  [-1 56  5 -1 -1]
  [11 88  7 37 73]]]


##10. Work with broadcasting and advanced operations in NumPy.
##Create a NumPy array arr of shape (3, 3) with random integers between
##1 and 20. Perform the following:


• Subtract the mean of each row from its respective elements (row-wise
normalization).

In [67]:
arr = np.random.randint(1, 20, (3, 3))
print(arr)
print(arr - arr.mean(axis=1))

[[ 6  6  6]
 [10 11 17]
 [17  4 18]]
[[ 0.         -6.66666667 -7.        ]
 [ 4.         -1.66666667  4.        ]
 [11.         -8.66666667  5.        ]]


• Create a new array by squaring all the elements in arr.

In [68]:
newarr = arr ** 2
print(newarr)

[[ 36  36  36]
 [100 121 289]
 [289  16 324]]


• Find the indices of the top 3 maximum values in the entire array.

In [69]:
print(np.argsort(arr, axis=None)[-3:])

[5 6 8]
